### ISSUE TITLE
`IndexError: tuple index out of range` in Snakemake file related to Nextalign rule, line 127

### ISSUE THREAD

**Issue by DOH-LMT2303** [nextstrain/monkeypox#139]
### Current Behavior
An error is triggered when the monkepox pipeline is run using snakemake. The chunk code that starts in line 127 which executes Nextalign fails. This part of the code can be run directly in command line and the output is produced correctly but this extra step is not ideal.

### Expected behavior
Snakemake to execute all the jobs without failing in line 127

### How to reproduce
Steps to reproduce the current behavior:
1. Install Nextstrain using the Ambient directions
2. Install the monkeypox Nextstrian pipeline according to instructions
3.  Run the pipeline after the installations is completed using the command `snakemake -j 1 -p --configfile config/config_hmpxv1.yaml`
4. See error:

```txt
Job 8: 
        Aligning sequences to config/reference.fasta
          - filling gaps with N
        
Reason: Missing output files: results/hmpxv1/aligned.fasta

RuleException in rule align in line 127 of /home/lmarcelat/monkeypox/workflow/snakemake_rules/core.smk:
IndexError: tuple index out of range, when formatting the following:

        nextalign run             --jobs {3}             --reference {input.reference}             --genemap {input.genemap}             --max-indel {params.max_indel}             --seed-spacing {params.seed_spacing}             --retry-reverse-complement             --output-fasta -             --output-insertions {output.insertions}             {input.sequences} | seqkit seq -i > {output.alignment}
```

### My environment: if running Nextstrain locally
Windows operating system running locally using WSL

**Comment by tsibley** [comment]
Ah, just realized there's some more context here in https://github.com/DOH-SML1303/wa_mpxv/commit/95a3d708be91bd22ccae30b21b4e40841170ab1d#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R11-R15

**Comment by tsibley** [comment]
Hi Marcella (@DOH-LMT2303), can you share the exact error you're seeing? A screenshot would be good, or even better, a full copy of the `snakemake` output:

```
snakemake -j 1 -p --configfile config/config_hmpxv1.yaml >log.txt 2>&1
```

then drag-and-drop the `log.txt` file onto a comment here on GitHub.

**Comment by tsibley** [comment]
From the [additional context](https://github.com/DOH-SML1303/wa_mpxv/commit/95a3d708be91bd22ccae30b21b4e40841170ab1d#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R11-R15), I do expect that we need to add `tsv-utils` and `seqkit` to the ambient runtime installation example. But not sure yet if that's the only issue here.

**Comment by corneliusroemer** [comment]
Thanks Marcela @DOH-LMT2303 for opening this issue and pointing us to the fact that the `ambient` runtime instructions are not sufficient to run this workflow. You need to add `tsv-utils` and `seqkit` as @tsibley indicated.

I added a note about this to the README.md in https://github.com/nextstrain/monkeypox/commit/0a61671f685694a6c8e0b9e18cb5baf85eea8b00

I assume this is the problem here so will close for now - let us know (with more error details) if the problem persists and we'll reopen.

**Comment by DOH-LMT2303** [comment]
@tsibley   I had installed `tsv-utils` and `seqkit` as I described in this commit https://github.com/DOH-SML1303/wa_mpxv/commit/95a3d708be91bd22ccae30b21b4e40841170ab1d#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R11-R15 

Those installations fixed other errors that were triggered  when executing the pipeline (thank you for editing the README.md file @corneliusroemer ). However, the chunk of code that starts in line 127 of the Snakemake file which executes Nextalign continues to fail. 

Here is a copy of the `snakemake` output. Thank you both!
[log.txt](https://github.com/nextstrain/monkeypox/files/10160418/log.txt)

**Comment by corneliusroemer** [comment]
Thanks

**Comment by corneliusroemer** [comment]
@DOH-LMT2303 I cannot reproduce your error. It would be good if you could try to get the same error on another machine, maybe with a colleague - since you're using this workflow with custom input/parameters that's probably the root cause.

This `IndexError: tuple index out of range, when formatting the following:` indicates a snakemake error due to some misconfiguration. What's in your configfile?

**Comment by tsibley** [comment]
@corneliusroemer I don't think this is a config file issue. At least, I don't see how it could be inspecting the log file Marcela provided and our workflow. That said, I can't reproduce with our workflow without modifying it.

@DOH-LMT2303 Are there any modifications to the monkeypox workflow you're running compared to https://github.com/nextstrain/monkeypox? Can you share your `workflow/snakemake_rules/core.smk` file?

From your logs, the issue is that the `rule align` shell block is seemingly using

    --jobs {3}

instead of the expected

    --jobs {threads}

and the resulting error is because Snakemake can't [interpolate/format the shell block](https://github.com/snakemake/snakemake/blob/d4484e61ef49be23fc2bef8bf879185e521f5376/snakemake/jobs.py#L941-L970) because `3` refers to a non-existent argument passed for interpolation/formatting.

**Comment by DOH-LMT2303** [comment]
@tsibley exactly, the way I have been able to overcome that error is by executing the commands manually which includes entering 
```
--jobs 3
``` 

```
nextalign run --jobs 3 --reference config/reference.fasta --genemap config/genemap.gff --max-indel 10000 --seed-spacing 1000 --retry-reverse-complement --output-fasta - --output-insertions results/hmpxv1/insertions.fasta results/hmpxv1/reversed.fasta | seqkit seq -i > results/hmpxv1/aligned.fasta`
```

I don't think I made any modifications to the monkeypox workflow. Here is the `workflow/snakemake_rules/core.smk` file
[core.txt](https://github.com/nextstrain/monkeypox/files/10170792/core.txt)

**Comment by corneliusroemer** [comment]
It looks like you have modified the align rule, you replaced 

```sh
 shell:
        """
        nextalign run \
            --jobs {threads} \
            --reference {input.reference} \
            --genemap {input.genemap} \
            --max-indel {params.max_indel} \
            --seed-spacing {params.seed_spacing} \
            --retry-reverse-complement \
            --output-fasta - \
            --output-insertions {output.insertions} \
            {input.sequences} | seqkit seq -i > {output.alignment}
        """
```

with

```
    shell:
        """
        nextalign run \
            --jobs {3} \
            --reference {input.reference} \
            --genemap {input.genemap} \
            --max-indel {params.max_indel} \
            --seed-spacing {params.seed_spacing} \
            --retry-reverse-complement \
            --output-fasta - \
            --output-insertions {output.insertions} \
            {input.sequences} | seqkit seq -i > {output.alignment}
        """
```

Replace the `{3}` with `{threads}` and things should work again.

**Comment by DOH-LMT2303** [comment]
@tsibley and @corneliusroemer I ran `git status` and sure enough I had modified the rule when that chunk of code first failed. I reverted that change from --jobs {3} to --jobs {threads} and reran the pipeline using `snakemake`. No errors were triggered. It seems that the issues were first triggered by the need to install `tsv-utils` and `seqkit`. Thank you.

**Comment by corneliusroemer** [comment]
Great to hear the issue was resolved :) We've now added a note about tsv-utils and seqkit so let's hope this is of use to future users!
