### ISSUE TITLE
ingest: use location hierarchy to help geolocation curation

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/monkeypox#35]
### Context
Use our [standardized location hierarchy](https://github.com/nextstrain/ncov-ingest/blob/master/source-data/location_hierarchy.tsv) that the ncov shepherds have curated in ncov-ingest to help with automating geolocation rules curation (#34). 

### Description
Ideally, the location hierarchy TSV will be stored in a centralized location (could be within `augur/augur/data/`), but for now we can just pull the file from ncov-ingest.

**Comment by MoiraZuber** [comment]
Unfortunately, we stopped curating location hierarchies a while back when the numbers grew too big to handle. This means these location hierarchies are at best outdated and might not be very useful. We could maybe start up a fresh file for monkeypox. Another possibility would be to utilize our current [curation script](https://github.com/nextstrain/ncov/blob/master/scripts/curate_metadata/curate_metadata.py) for use on monkeypox. Since it uses the same metadata structure, adjusting the script should not be too cumbersome.

**Comment by corneliusroemer** [comment]
Has this been fixed by now @joverlee521 ? If I remember correctly, we use some sort of hierarchy now?

**Comment by joverlee521** [comment]
@corneliusroemer This is a separate issue to use the location hierarchy to help with the geolocation rules curation process. However, I'll close this issue since I want to address this issue in the new `augur curate` command rather then putting the work here.
